"""Add inventory ledger and soft reservation models

Revision ID: 9ba43f0d0011
Revises: 1ccf3357870a
Create Date: 2026-07-06 23:58:25.860757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9ba43f0d0011'
down_revision: Union[str, Sequence[str], None] = '1ccf3357870a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_locations',
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_sellable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_tenant_location_code')
    )
    op.create_index(op.f('ix_stock_locations_code'), 'stock_locations', ['code'], unique=False)
    op.create_index(op.f('ix_stock_locations_id'), 'stock_locations', ['id'], unique=False)
    op.create_index(op.f('ix_stock_locations_name'), 'stock_locations', ['name'], unique=False)
    op.create_index(op.f('ix_stock_locations_tenant_id'), 'stock_locations', ['tenant_id'], unique=False)
    op.create_table('stock_balances',
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('physical_qty', sa.Integer(), nullable=False),
    sa.Column('reserved_qty', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('physical_qty >= 0', name='ck_physical_qty_non_negative'),
    sa.CheckConstraint('physical_qty >= reserved_qty', name='ck_no_over_reservation'),
    sa.CheckConstraint('reserved_qty >= 0', name='ck_reserved_qty_non_negative'),
    sa.ForeignKeyConstraint(['location_id'], ['stock_locations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'product_id', 'location_id', name='uq_tenant_prod_loc')
    )
    op.create_index(op.f('ix_stock_balances_id'), 'stock_balances', ['id'], unique=False)
    op.create_index(op.f('ix_stock_balances_location_id'), 'stock_balances', ['location_id'], unique=False)
    op.create_index(op.f('ix_stock_balances_product_id'), 'stock_balances', ['product_id'], unique=False)
    op.create_index(op.f('ix_stock_balances_tenant_id'), 'stock_balances', ['tenant_id'], unique=False)
    op.create_table('stock_ledgers',
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('physical_delta', sa.Integer(), nullable=False),
    sa.Column('reserved_delta', sa.Integer(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('reference_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['stock_locations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name='uq_tenant_idempotency')
    )
    op.create_index(op.f('ix_stock_ledgers_id'), 'stock_ledgers', ['id'], unique=False)
    op.create_index(op.f('ix_stock_ledgers_idempotency_key'), 'stock_ledgers', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_stock_ledgers_location_id'), 'stock_ledgers', ['location_id'], unique=False)
    op.create_index(op.f('ix_stock_ledgers_product_id'), 'stock_ledgers', ['product_id'], unique=False)
    op.create_index(op.f('ix_stock_ledgers_reason'), 'stock_ledgers', ['reason'], unique=False)
    op.create_index(op.f('ix_stock_ledgers_reference_id'), 'stock_ledgers', ['reference_id'], unique=False)
    op.create_index(op.f('ix_stock_ledgers_tenant_id'), 'stock_ledgers', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_ledgers_tenant_id'), table_name='stock_ledgers')
    op.drop_index(op.f('ix_stock_ledgers_reference_id'), table_name='stock_ledgers')
    op.drop_index(op.f('ix_stock_ledgers_reason'), table_name='stock_ledgers')
    op.drop_index(op.f('ix_stock_ledgers_product_id'), table_name='stock_ledgers')
    op.drop_index(op.f('ix_stock_ledgers_location_id'), table_name='stock_ledgers')
    op.drop_index(op.f('ix_stock_ledgers_idempotency_key'), table_name='stock_ledgers')
    op.drop_index(op.f('ix_stock_ledgers_id'), table_name='stock_ledgers')
    op.drop_table('stock_ledgers')
    op.drop_index(op.f('ix_stock_balances_tenant_id'), table_name='stock_balances')
    op.drop_index(op.f('ix_stock_balances_product_id'), table_name='stock_balances')
    op.drop_index(op.f('ix_stock_balances_location_id'), table_name='stock_balances')
    op.drop_index(op.f('ix_stock_balances_id'), table_name='stock_balances')
    op.drop_table('stock_balances')
    op.drop_index(op.f('ix_stock_locations_tenant_id'), table_name='stock_locations')
    op.drop_index(op.f('ix_stock_locations_name'), table_name='stock_locations')
    op.drop_index(op.f('ix_stock_locations_id'), table_name='stock_locations')
    op.drop_index(op.f('ix_stock_locations_code'), table_name='stock_locations')
    op.drop_table('stock_locations')
    # ### end Alembic commands ###
